package system;

public enum StatusCodes {
    OK,
    AGENT_DOES_NOT_EXIST,
    AGENT_NOT_LOGGED_IN,
    SESSION_KEY_INVALID_LENGTH,
    SESSION_KEY_UNRECOGNIZED,
    MESSAGE_LENGTH_EXCEEDED,
    SOURCE_AGENT_QUOTA_EXCEEDED,
    TARGET_AGENT_QUOTA_EXCEEDED,
    BOTH_AGENT_QUOTAS_EXCEEDED,
    FAILED_TO_ADD_TO_MAILBOX,
    GENERIC_ERROR // intended for use in testing
}
